# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mock Starket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxStarscream'
  pod 'RxDataSources'
  pod 'SwiftyJSON'
  pod 'Starscream'
  pod 'Charts'
  pod 'Alamofire'
  pod 'SideMenu'
  pod 'Fabric'
  pod 'Crashlytics'
 
# Pods for Mock Starket
    target 'Mock StarketTests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
    end

    target 'Mock StarketUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
